### ISSUE TITLE
Insert Parameters

### ISSUE THREAD

**Issue by DovahCraft** [DovahCraft/PartialSetModelSelection#10]
@tdhock For the insert methods, I currently have two parameters, 

insert(double penalty, Model model) 

where model is a struct I have defined in the PartialModelSelection.hpp file.

However, as I think about how to best implement this as an R package, should I instead have the insert method (or perhaps a wrapper of it?) that manually takes in the penalty, model_size, and loss for each model to be inserted instead? That way I can create the model struct within the method and then insert it with a penalty key to my map, rather than having the model struct itself as a penalty to insert which may add friction to use in an R package as the user would have to define the model struct before insertion using a simple constructor.

Thanks

**Comment by tdhock** [comment]
yes in R the user would provide numeric/integer vectors to your method
probably (see Rcpp modules vignette for details) so I think it makes more
sense to make that Model struct an internal implementation detail, if you
need it

**Comment by DovahCraft** [comment]
Ok I will refactor that such that the public method takes in the values and uses them to make the struct, which I then will use internally. Thanks!
