### ISSUE TITLE
std::map lower_bound is not named well..

### ISSUE THREAD

**Issue by DovahCraft** [DovahCraft/PartialSetModelSelection#11]
@tdhock We were talking about the usage of lower_bound for both the insert and minimize functions and how I could use it to update the previous and next keys for an entry if they exist. 

According to the cpp reference for [std::map's lower_bound method ](http://www.cplusplus.com/reference/map/map/lower_bound/ ), lower bound returns the first value that is not considered to go **before** the parameter query k. This does not make sense in the terms of a lower_bound, as this means that the key returned from lower_bound is quote "is equivalent or goes after", whereas upper_bound functions the same, but does not include the query itself if the key queried is indeed in the map already. 

As I am developing insert and updating the after entries for both a new insertion and the entry before it, I am using lower_bound to find:

the key after my new penalty being inserted: **penaltyModelMap.lower_bound(newPenalty)**

and then the key before my new penalty (if there is one) using prev on the iterator found above: **prev(penaltyModelMap.lower_bound(newPenalty))**

Note that I check for duplicate keys by parsing the result of the std::map insert method itself, so the newPenalty key will not be returned from lower_bound (unless it is the placeholder key of 0.0, which I then just update if I have a manual insert of a model at penalty key 0.).

What do you think of this approach? Do you agree with my assessment of lower_bound here? Thanks!

**Comment by DovahCraft** [comment]
I also created a test called testLowerBoundInsertion yesterday as I was exploring how this behavior would interact with my access to the data structure. If you want to take a look it is under the InsertTests test suite. Please look at the Minimize/Insertions branch to find it in the PartialModelSelectionMain.cpp file.

**Comment by tdhock** [comment]
hi can you please clarify your question? I don't understand what you are trying to ask.
good that you are looking at the C++ STL docs about the map methods such as lower_bound.

**Comment by tdhock** [comment]
If you want me to review code like your testLowerBoundInsertion please create a PR then click "commits" or "files changed" tab and then make a comment on the relevant line of code and tag me.
