### ISSUE TITLE
Removal of penalties in getNewPenaltyList

### ISSUE THREAD

**Issue by DovahCraft** [DovahCraft/PartialSetModelSelection#21]
@tdhock I currently am storing the correct values in the getNewPenaltyList that correspond to new breakpoint penalties we should query. However, if there is an insertion at one of the penalties, should I remove the suggested penalty value from the list?

I think we should, but the std::vector erase method is O(n) time in the number of penalties we have stored. Would this make the whole algorithm O(n) without much benefit? Would it be considered amortized linear time? Want to see your opinion on this when possible.

**Comment by tdhock** [comment]
you are right, we should remove, and removal with a vector is O(n) which is too slow. using a map or list you could get O(1) removal.
