### ISSUE TITLE
Solve sub routine?

### ISSUE THREAD

**Issue by JoeyV55** [DovahCraft/PartialSetModelSelection#23]
@tdhock What exactly should we do with the solve subroutine? I saw that you mentioned that one again in the google doc, but I am not sure what it does in addition to what Insert, Minimize, and getNewPenalty do.

**Comment by JoeyV55** [comment]
"use maps::erase to delete model during solve sub-routine"

**Comment by tdhock** [comment]
the solve sub-routine is Algorithm 2 of our paper

**Comment by JoeyV55** [comment]
@tdhock Hey Dr. Hocking, I am sitting down to try and implement the two parameter insert based on what we discussed. You said that you already had a solution in mind.

Should I tie the first insertion to a key of INFINITY?
Should I still use the largestModelInserted iterator? Or would I need more of them? I am thinking about a middle insertion where I would potentially need to update models that are both larger and smaller than my current insertion.

For example, if we look at the right panel of Fig 1, what would need to happen if I inserted in this order:

Model 3 at 2.0 loss
Model 1 at 7.0 loss
Model 2 at 4.0 loss

You said that this should take O(nlg(n)) time right?

**Comment by tdhock** [comment]
Should I tie the first insertion to a key of INFINITY? -> yes or 0 depending on how you want to represent it (do you want to store model size before or after the penalty=key value?)

Should I still use the largestModelInserted iterator? Or would I need more of them? -> probably still only need one iterator. say you have 100 keys/models already inserted, and you want to insert a new one in the middle, you should do binary search (on model size values) to find the place/iterator where you need to do the insertion/deletion, and then just use that one iterator.

You said that this should take O(nlg(n)) time right? -> binary search takes O(log N) time, insertion/deletion should be amortized constant time, so overall inserting N models should be O(N log N) yes.

**Comment by JoeyV55** [comment]
Hmm, lower_bound seems to already be implemented with binary search, but that would do a binary search on our keys, which is not useful. 

Should I use the size of the map / 2 to find the middle using a for loop and the next() iterator function? Then my binary search on model_size will allow me to find a slot to consider placing my new model I am inserting? 

Binary search is straightforward for sorted arrays, but I am having trouble conceptualizing it for this map. The map is naturally sorted as the lowest key corresponds to the highest model_size available.

**Comment by JoeyV55** [comment]
@tdhock So for 100 keys, 

I would need to find the middle key, get its model size, and then see:

If its modelsize equals my current model size (would this cause an error?)
If its modelsize is less than my current model size (so search the left side of the map, recomputing the middle of the left side)
If its modelsize is greater than my current model size (so search the right side of the map, recomputing the middle of the right side)

When would the search terminate? The goal is to place the candidate model for insertion between two iterators:

firstIterator.modelSize > newInsertion.modelSize
secondIterator.modelSize < newInsertion.modelSize

Then would I work similarly to the previous algorithm? With a loop computing breakpoints with first iterator and another computing breakpoints with the second iterator?

**Comment by tdhock** [comment]
don't code binary search yourself, use https://en.cppreference.com/w/cpp/algorithm/binary_search

**Comment by JoeyV55** [comment]
Okay that will simplify that. I didn't know I could apply the std::binary search directly to this map structure.

**Comment by JoeyV55** [comment]
@tdhock Uh I don't think that will work. The binary search method you linked is built for vectors, not this map. I am having type errors as std::binary_search cannot use the key of each pair inserted to the map.

**Comment by JoeyV55** [comment]
From stdalgo.h

error: no match for ‘operator<’ (operand types are ‘const int’ and ‘std::pair<const double, Model>’)
 2259 |       return __i != __last && !(__val < *__i);

**Comment by tdhock** [comment]
well maybe you need to use model sizes as keys then?

**Comment by JoeyV55** [comment]
@tdhock That might be a possibility, let's talk tomorrow. The main problem above is that maps are indexed with std::pairs, so having a model size as a key would not make a difference. std::binary_search needs single elements, such as iterators to doubles, ints, and so on, so it can compare elements and perform the search.

Lower_bound is actually an adapted binary search to work with map pairings, but I am still working out how exactly to use it to help in this situation.
