### ISSUE TITLE
R package interface

### ISSUE THREAD

**Issue by tdhock** [DovahCraft/PartialSetModelSelection#6]
I would suggest creating the interface using Rcpp modules, please read this https://cloud.r-project.org/web/packages/Rcpp/vignettes/Rcpp-modules.pdf to see how to do that

**Comment by DovahCraft** [comment]
Ok great, so I can write unit tests with Rcpp and not have to use gtest? I will read this today.

**Comment by DovahCraft** [comment]
Its unfortunate because I do like gtest, but it has been so difficult to integrate it with other technologies that it is simply not worth it imo.

**Comment by tdhock** [comment]
no you can't write unit tests with Rcpp.
You can write an R interface for your C++ code using Rcpp.
Then you can write R code that calls your insert/minimize/etc methods.
And I would suggest writing tests in R code using
https://r-pkgs.org/tests.html

**Comment by DovahCraft** [comment]
Great thanks for the info on that.

**Comment by tdhock** [comment]
Also would be good for you to read some other parts of that book, starting from the beginning, to learn more about how to write your own R package.

**Comment by DovahCraft** [comment]
Do you think it would be ok if I continued to implement the C++ code with the test suite I have with gtest and then port it over to R unit tests and set up CI at that time too?

Gtest is working well for my development of the core data structure itself, so I wanted to see if I could get that done first. (or at least most of it..)

**Comment by tdhock** [comment]
yes that is fine
you can work on both in parallel if you want

**Comment by DovahCraft** [comment]
Great will do, thanks for the help!

**Comment by DovahCraft** [comment]
@tdhock Have you ever used Circle CI? I was going to look into it and see if it is easy to use with gtest than Travis CI.

**Comment by tdhock** [comment]
no I have only experience with appveyor, wercker and travis. but please try circle ci if you think it may work. google is your friend. (others must have already got google test working on these platforms)
